username_input = '//*[@id="txtUsername"]'
userpassword_input = '//*[@id="txtPassword"]'
login_button = '//*[@id="btnLogin"]'
hoveradmin = '//*[@id="menu_admin_viewAdminModule"]/b'
hoverusermanagement = '//*[@id="menu_admin_UserManagement"]'
users = '//*[@id="menu_admin_viewSystemUsers"]'
adduser = '//*[@id="btnAdd"]'
employeename_input = '//*[@id="systemUser_employeeName_empName"]'
add_user_name_input = '//*[@id="systemUser_userName"]'
status_dropdown = '//*[@id="systemUser_status"]'
add_user_passwword_input = '//*[@id="systemUser_password"]'
add_user_confirm_passwword_input ='//*[@id="systemUser_confirmPassword"]'
add_user_save_btn = '//*[@id="btnSave"]'
user_drop_down = '//*[@id="systemUser_userType"]'
select_from_search_result = '//div[@class="ac_results"]'
